name: Build Android APK

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Clean npm cache
        run: npm cache clean --force

      - name: Install npm dependencies
        run: |
          npm config set registry https://registry.npmjs.org/
          npm ci --legacy-peer-deps --no-audit --no-fund --verbose

      - name: Debug npm dependencies
        run: npm list --depth=0 || true

      - name: Post install (Jetify)
        run: npx jetify || true

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3

      - name: Cache Gradle dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}-v2
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Make gradlew executable
        run: |
          cd android
          chmod +x ./gradlew

      - name: Pre-bundle Metro (Optional)
        env:
          NODE_OPTIONS: --max_old_space_size=4096
        run: |
          npx react-native bundle \
            --platform android \
            --dev false \
            --entry-file index.js \
            --bundle-output android/app/src/main/assets/index.android.bundle \
            --assets-dest android/app/src/main/res \
            --verbose || true

      - name: Build APK
        env:
          MYAPP_RELEASE_STORE_PASSWORD: ${{ secrets.STORE_PASSWORD }}
          MYAPP_RELEASE_KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
          MYAPP_RELEASE_KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
          NODE_OPTIONS: --max_old_space_size=4096
        run: |
          cd android
          ./gradlew clean --refresh-dependencies
          ./gradlew assembleRelease --stacktrace --info --no-daemon --console=plain

      - name: Upload APK
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: app-release.apk
          path: android/app/build/outputs/apk/release/app-release.apk
